### ISSUE TITLE
Seene Members window scrolling on 5s

### ISSUE THREAD

**Issue by neopaf** [seene-club/Open-Seene#2]
refuses to scroll, can't follow Wayne and other beloved posters :(

**Comment by chiaroscurosity** [comment]
I also have this issue. I tried to follow myself and other members using an iPad because the screen is bigger but I have the same issue. Members who appear at the bottom of the list are not able to be followed due to limited scrolling. The list snaps back when you scroll down to a certain point. It seems to affect both iPhone 5s as well as iPad.
![photo1240837905064241067](https://cloud.githubusercontent.com/assets/16271921/20589804/a10d56d8-b1d3-11e6-8ce2-1dc1122267af.jpg)

**Comment by seene-club** [comment]
should also be fixed in alpha release 0.11. Please test for me, I don't have these devices ... thanks!

**Comment by seene-club** [comment]
does this work for you @neopaf? close?

**Comment by neopaf** [comment]
it does. thanks, Mathias!
